INSERT INTO `Countries` VALUES
('1','Anguilla'),
('2','Saint Pierre and Miquelon'),
('3','Romania'),
('4','Afghanistan'),
('5','Jersey'),
('6','Morocco'),
('7','Antigua and Barbuda'),
('8','Somalia'),
('9','China'),
('10','Slovenia'),
('11','Guadeloupe'),
('12','South Georgia and the South Sandwich Islands'),
('13','Palestinian Territory'),
('14','Colombia'),
('15','Oman'),
('16','Nauru'),
('17','Mauritania'),
('18','Christmas Island'),
('19','Suriname'),
('20','New Zealand'),
('21','Lao People\'s Democratic Republic'),
('22','Peru'),
('23','Holy See (Vatican City State)'),
('24','Finland'),
('25','Thailand'),
('26','Cuba'),
('27','Denmark'),
('28','Norfolk Island'),
('29','Mauritania'),
('30','Mauritania'),
('31','Barbados'),
('32','Tanzania'),
('33','Egypt'),
('34','Lao People\'s Democratic Republic'),
('35','United States Virgin Islands'),
('36','Ukraine'),
('37','Swaziland'),
('38','Germany'),
('39','Malaysia'),
('40','Djibouti'),
('41','Trinidad and Tobago'),
('42','Libyan Arab Jamahiriya'),
('43','Guinea-Bissau'),
('44','Singapore'),
('45','Kyrgyz Republic'),
('46','Bosnia and Herzegovina'),
('47','Serbia'),
('48','Jersey'),
('49','Spain'),
('50','Macao'),
('51','Ecuador'),
('52','Saint Kitts and Nevis'),
('53','Bhutan'),
('54','Papua New Guinea'),
('55','Kuwait'),
('56','Kenya'),
('57','Mali'),
('58','Cocos (Keeling) Islands'),
('59','Austria'),
('60','Spain'),
('61','Saint Barthelemy'),
('62','Saint Barthelemy'),
('63','Mali'),
('64','Costa Rica'),
('65','Thailand'),
('66','Bhutan'),
('67','Cambodia'),
('68','Northern Mariana Islands'),
('69','Mauritania'),
('70','Latvia'),
('71','Tajikistan'),
('72','Maldives'),
('73','Belize'),
('74','Uganda'),
('75','Macao'),
('76','Tanzania'),
('77','Suriname'),
('78','Macedonia'),
('79','Ecuador'),
('80','Algeria'),
('81','Ireland'),
('82','Iceland'),
('83','Slovenia'),
('84','Pitcairn Islands'),
('85','Mauritania'),
('86','Brazil'),
('87','Slovakia (Slovak Republic)'),
('88','Gabon'),
('89','Turks and Caicos Islands'),
('90','Antarctica (the territory South of 60 deg S)'),
('91','Papua New Guinea'),
('92','United Arab Emirates'),
('93','Djibouti'),
('94','Bolivia'),
('95','Ukraine'),
('96','Bangladesh'),
('97','Saudi Arabia'),
('98','Venezuela'),
('99','Cambodia'),
('100','Niger');

