LOAD DATA INFILE 'C:/mysql/users.csv' INTO TABLE users FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n';
LOAD DATA INFILE 'C:/mysql/payments.csv' INTO TABLE payments  FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n';
LOAD DATA INFILE 'C:/mysql/sessions.csv' INTO TABLE sessions  FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n';