INSERT INTO Disciplines VALUES
(1, 'Dota2'),
(2, 'Counter_Strike: Global Offensive'),
(3, 'Fortnite'),
(4, 'League of Legends'),
(5, 'StarCraft II'),
(6,	'PLAYERUNKNOWN’S BATTLEGROUNDS'),
(7,	'Overwatch'),
(8,	'Hearthstone'),
(9,	'Heroes of the Storm'),	
(10, 'Arena of Valor'),
(11, 'Counter-Strike'),	
(12, 'Rainbow Six Siege'),	
(13, 'SMITE'),
(14, 'Rocket League'),
(15, 'StarCraft: Brood War'),
(16, 'Call of Duty: Black Ops 4'),
(17, 'Halo 5: Guardians'),
(18, 'CrossFire'),
(19, 'WarCraft III'),
(20, 'Magic: The Gathering Arena');
