INSERT INTO positions (position_name) VALUES ("Captain");
INSERT INTO positions (position_name) VALUES ("Head of Personnel");
INSERT INTO positions (position_name) VALUES ("Head of Security");
INSERT INTO positions (position_name) VALUES ("Security Officer");
INSERT INTO positions (position_name) VALUES ("Warden");
INSERT INTO positions (position_name) VALUES ("Detective");
INSERT INTO positions (position_name) VALUES ("Chief Engineer");
INSERT INTO positions (position_name) VALUES ("Station Engineer");
INSERT INTO positions (position_name) VALUES ("Atmospheric Technician");
INSERT INTO positions (position_name) VALUES ("Research Director");
INSERT INTO positions (position_name) VALUES ("Geneticist");
INSERT INTO positions (position_name) VALUES ("Scientist");
INSERT INTO positions (position_name) VALUES ("Roboticist");
INSERT INTO positions (position_name) VALUES ("Chief Medical Officer");
INSERT INTO positions (position_name) VALUES ("Medical Doctor");
INSERT INTO positions (position_name) VALUES ("Paramedic");
INSERT INTO positions (position_name) VALUES ("Chemist");
INSERT INTO positions (position_name) VALUES ("Virologist");
INSERT INTO positions (position_name) VALUES ("Janitor");
INSERT INTO positions (position_name) VALUES ("Bartender");
INSERT INTO positions (position_name) VALUES ("Cook");
INSERT INTO positions (position_name) VALUES ("Botanist");
INSERT INTO positions (position_name) VALUES ("Clown");
INSERT INTO positions (position_name) VALUES ("Mime");
INSERT INTO positions (position_name) VALUES ("Chaplain");
INSERT INTO positions (position_name) VALUES ("Curator");
INSERT INTO positions (position_name) VALUES ("Quartermaster");
INSERT INTO positions (position_name) VALUES ("Cargo Technician");
INSERT INTO positions (position_name) VALUES ("Shaft Miner");
INSERT INTO positions (position_name) VALUES ("Assistant");
INSERT INTO positions (position_name) VALUES ("Lawyer");
INSERT INTO positions (position_name) VALUES ("Psychologist");
INSERT INTO positions (position_name) VALUES ("Prisoner");
INSERT INTO positions (position_name) VALUES ("AI");
INSERT INTO positions (position_name) VALUES ("Cyborg");
INSERT INTO positions (position_name) VALUES ("Positronic Brain");
INSERT INTO positions (position_name) VALUES ("Drone");
INSERT INTO positions (position_name) VALUES ("Personal AI");
INSERT INTO positions (position_name) VALUES ("Construct");

-- SELECT * FROM positions;