USE UserPaymentSession;
CREATE TABLE IF NOT EXISTS users (
    user_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    login VARCHAR(50) NOT NULL,
    reg_dttm TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);